language: python
python:
    - "2.7"
virtualenv:
  system_site_packages: true
before_install:
    - sudo apt-get -qq install python-numpy python-scipy
install:
    - python setup.py install
script:
    - python code/trlda/python/tests/batchlda_test.py
    - python code/trlda/python/tests/onlinelda_test.py
    - python code/trlda/python/tests/utils_test.py
